// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerApi.Models;

#nullable disable

namespace TaskManagerApi.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerApi.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "it's a test",
                            DueDate = "12-23-2024",
                            Status = 0,
                            Title = "do something"
                        },
                        new
                        {
                            Id = 2,
                            Description = "it's a test",
                            DueDate = "12-23-2024",
                            Status = 1,
                            Title = "do something"
                        },
                        new
                        {
                            Id = 3,
                            Description = "another test",
                            DueDate = "01-15-2025",
                            Status = 2,
                            Title = "do something else"
                        },
                        new
                        {
                            Id = 4,
                            Description = "final test",
                            DueDate = "02-10-2025",
                            Status = 0,
                            Title = "complete project"
                        },
                        new
                        {
                            Id = 5,
                            Description = "code review task",
                            DueDate = "03-05-2025",
                            Status = 1,
                            Title = "review code"
                        },
                        new
                        {
                            Id = 6,
                            Description = "documentation task",
                            DueDate = "03-20-2025",
                            Status = 2,
                            Title = "write documentation"
                        },
                        new
                        {
                            Id = 7,
                            Description = "bug fixing task",
                            DueDate = "04-01-2025",
                            Status = 0,
                            Title = "fix bugs"
                        },
                        new
                        {
                            Id = 8,
                            Description = "deployment task",
                            DueDate = "04-15-2025",
                            Status = 1,
                            Title = "deploy application"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
